### ISSUE TITLE
Markdown 双星号强调时加入了多余空格

### ISSUE THREAD

**Issue by laggardkernel** [baurine/vscode-pangu#1]
在 Markdown 中使用双星号强调时，如果强调内容为中文，例如 `**注**` ，会引入多余空格。最后格式化为 `** 注 **` 。但是使用双下划线 `__注__` 强调时不存在此问题。

**Comment by wytsai7660** [comment]
不好意思過了這麼久把這個issue挖起來，請問關於這個issue的修復版本是不是沒有發布至VScode Marketplace？我在VScode內載到的還是會發生同樣問題。

（btw真的很謝謝你做了這個extension，非常實用）
