### ISSUE TITLE
建议不要触动 markdown 反引号中代码

### ISSUE THREAD

**Issue by laggardkernel** [baurine/vscode-pangu#2]
markdown 中 JS 代码尝试以两个空格缩进输出 JSON 化字符串。

```javascript
json = JSON.stringify(dict, null, '  ');
```

格式化后两个空格缩进被改为了一个空格。

**Comment by baurine** [comment]
hi @laggardkernel ，谢谢你的反馈，你提交的这两个反馈 (包括 #1 )，都是已知的问题。

是这样的，加空格的核心算法是由 [pangu](https://github.com/vinta/pangu.js) 库来提供的，我这个插件相当于只是把它包装成可以在 VS Code 上使用，你说的关于 markdown 的问题在 pangu 的 issue 里也有：https://github.com/vinta/pangu.js/issues/91 。

**Comment by laggardkernel** [comment]
感谢你的答复。研究了一下pangu，这玩意儿基本就是几条正则匹配Unicode字符。

后来我想，正则替换同时顾及Markdown语法，单靠正则是很难做到的，应该先剔除或分离Markdown中标记与内容，再对内容进行处理。按照后面这种思路，Markdown加空格的事情应该归Markdown语法解析、渲染库管，因为它想要渲染Markdown就得给标记和内容做分离。最后我越想越觉得这件事不对劲儿，既然都归渲染管了，我在编辑过程中就没必要考虑神马空格了。中英文间空格被我归为一个渲染显示问题，不再是一个编辑问题。
